import Vue from 'vue'
//引入element-ui
import {
    Form,
    Input,
    FormItem,
    Button,
    Message,
    Container,
    Aside,
    Header,
    Main,
    Submenu,
    MenuItem,
    Menu,
    Breadcrumb,
    BreadcrumbItem,
    Card,
    Select,
    Option,
    Row,
    Col,
    Table,
    TableColumn,
    Switch,
    Tooltip,
    Pagination,
    Dialog,
    MessageBox,
    Tag,
    Tree,
    Cascader,
    Alert,
    Tabs,
    TabPane
    } from 'element-ui';


Vue.component(Form.name,Form);
Vue.component(Input.name,Input);
Vue.component(FormItem.name,FormItem);
Vue.use(Button);
Vue.use(Container);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Header);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(Menu);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(Card);
Vue.use(Select);
Vue.use(Option);
Vue.use(Row);
Vue.use(Col);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Switch);
Vue.use(Tooltip);
Vue.use(Pagination);
Vue.use(Dialog);
Vue.use(Tag);
Vue.use(Tree);
Vue.use(Cascader);
Vue.use(Alert);
Vue.use(Tabs);
Vue.use(TabPane);
//消息弹框
Vue.prototype.$message=Message;
Vue.prototype.$confirm=MessageBox.confirm